import { Head } from "../components";
import ReactMarkdown from "react-markdown/with-html";

export default () => {
  const markdown = `
  # Privacy Policy
  
  ### Effective as of October 2, 2019
  
  xgohorse.com conducting business under its tradename “XGH Certification" ("us", "we", or "our") operates the website located at https://xgohorse.com/ (the "Service").
  
  This page informs you of our policies regarding the collection, use, disclosure and protection of personal data when you use our Service and the choices you have associated with that data.  Please review this Privacy Policy before providing any personal data.  There is no requirement that you provide us with any of your personal data, and if you choose to do so, you may subsequently elect to “opt-out” or delete your personal data as described below, but please be aware that we will not be able to provide you with our products or any communication by or through the Service.
  
  We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.
  
  ## DEFINITIONS
  
  ### Service
  Service is the https://xgohorse.com/ website.
  
  ### Personal Data
  Personal Data means data about a living individual, who can be identified from that data (or from other information either in our possession or likely to come into our possession).
  
  ### Usage Data
  Usage Data is data collected automatically which is either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
  
  ### Google AdSense & DoubleClick Cookie
  Google, as a third party vendor, uses cookies to serve ads on our Service.

  ### Cookies
  Cookies are small pieces of data stored on your device (computer or mobile device).
  
  ### Data Controller
  Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information is, or will be, processed.  For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
  
  ### Data Processors (or Service Providers)
  Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
  
  ### Data Subject (or User)
  Data Subject is any living individual who is using our Service and is the subject of Personal Data.
  
  ### INFORMATION COLLECTION AND USE
  
  We collect several different types of information for various purposes to provide and improve our Service to you.
  
  ### Types of Data Collected 
  
  ### Personal Data 
  While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Information which is personally identifiable may include but is not limited to:
  
  - First name;
  - Cookies and Usage Data;
  - Device Identifiers (such as IP address or Cookie ID);


  ### Usage Data
  We may also collect information about how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
  
  ### Location Data 
  We may use and store information about your location if you provide us the ability to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.
  
  You can enable or disable location services when you use our Service at any time through your device settings.
  
  ### Tracking & Cookies Data 
  
  We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
  
  Cookies are files with small amounts of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies are also used, such as beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
  
  You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
  
  ### Examples of Cookies we use:
  Consent Cookies. We use Consent Cookie to remember your choice of cookie consent.
  Advertising Cookies. Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.
  Performance Cookies. These cookies allow us to count visits and traffic sources, so we can measure and improve the performance of our site. They help us know which pages are the most and least popular and see how visitors move around the site. All information these cookies collect is aggregated and therefore anonymous. If you do not allow these cookies, we will not know when you have visited our site.
  
  ### Use of Data 
  We use the collected data for various purposes, each of which you consent to by your use of the Service
  
  * To gather analysis or valuable information so that we can improve our Service;
  * To monitor the usage of our Service;


  ### Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)
  
  If you are from the European Economic Area (EEA), our legal basis for collecting and using the personal information described in this Privacy Policy is based upon consent, and with respect to specific information, depends on the Personal Data we collect and the specific context in which we collect it.
  
  We may process your Personal Data because:
  
  * We need to perform a contract with you;
  * You have given us permission to do so;
  * The processing is in our legitimate interests and is not overridden by your rights;
  * To comply with the law.


  ### RETENTION OF DATA
  
  We will retain your Personal Data only for as long as is reasonably necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
  
  We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time than Personal Data, except when Usage Data is used to strengthen the security or to improve the functionality of our Service, or where we are legally obligated to retain Usage Data for longer time periods.
  
  ### SHARING DATA
  
  We may enter into agreements and other arrangements with with one or more of our business partners for services related to our business, including, among other services, shipping, customer support, customer feedback, name and address verification, email distribution, market research, third party advertising, fraud prevention, promotions management and payment processing, and in connection with such services, we may provide our business partners with any information, including Usage Data and Personal Data, required by our business partners in order to perform their services.  We may also share Usage Data and your Personal Data with one or more of our business partners for the purpose of providing you with information relating to products and services that may be of interest to you, and you may be contacted by us or by our business partners to both describe and offer such products or services.  In each instance, we will take efforts to ensure that your privacy is respected and that all Usage Data and Personal Data are protected.
  
  Our business partners may also share information with us about you that they have independently developed or acquired in accordance with their respective privacy policies, in order to provide information to us so that we may better understand your interests and preferences and provide you with information relating to products and services that may be of particular interest to you. Any information that we receive from our business partners concerning you will be treated by us in the same manner as information we receive from you or develop in accordance with our Privacy Policy.  The legal basis for sharing your Usage Data and Personal Data with our business partners is based upon consent.
  
  ### TRANSFER OF DATA – Location
  
  Your information, including Personal Data, may be transferred to, and maintained on, computers located outside of your state, province, country or other governmental jurisdiction of residence where the data protection laws may differ from those from your jurisdiction.
  
  If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data to the United States and process it there.
  
  Your consent to this Privacy Policy followed by your submission of such Personal Data represents your agreement to that transfer.
  
  We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy, and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
  
  ### DISCLOSURE OF DATA
  
  ### Legal Requirements
  We may disclose your Personal Data in the good faith belief that such action is necessary to:
  
  * To comply with a legal obligation;
  * To protect and defend the rights or property of https://xgohorse.com;
  * To prevent or investigate possible wrongdoing in connection with the Service;
  * To protect the personal safety of users of the Service or the public, and
  * To protect against legal liability in connection with uses for which you have provided your consent.


  ### Security of Data 
  The security of your data is important to us but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means and practices to protect your Personal Data, we cannot guarantee its absolute security.
  
  ### "Do Not Track" Signals 
  We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
  
  You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
  
  ### Your Data Protection Rights Under General Data Protection Regulation (GDPR) 
  If you are a resident of the European Economic Area (EEA), you have certain data protection rights. We take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
  
  If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us at xghcertification@gmail.com.
  
  ### In certain circumstances, you have the following data protection rights:
  
  * The right to withdraw consent. You also have the right to withdraw your consent at any time where we relied on your consent to process your personal information.


  ### SERVICE PROVIDERS
  
  We may employ third-party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
  
  These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
  
  ### ANALYTICS
  
  We may use third-party Service Providers to monitor and analyze the use of our Service.
  
  ### Google Analytics
  Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.
  
  You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.
  
  For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: https://policies.google.com/privacy?hl=en.
  
  ### BEHAVIORAL REMARKETING
  
  We use remarketing services to advertise on third party websites to you after you visit our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.
  
  ### Google AdWords
  Google AdWords remarketing service is provided by Google Inc.
  
  You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: http://www.google.com/settings/ads.
  
  Google also recommends installing the Google Analytics Opt-out Browser Add-on (https://tools.google.com/dlpage/gaoptout) for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.
  
  For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: https://policies.google.com/privacy?hl=en.

  ### LINKS TO OTHER SITES
  
  Our Service may contain links to other sites that are not operated by us. If you click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
  
  We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.
  
  ### CHILDREN'S PRIVACY
  
  Our Service does not address anyone under the age of 18 ("Children").
  
  We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
  
  ### CHANGES TO THIS POLICY
  
  We may update our Privacy Policy from time to time.
    
  You are advised to review this Privacy Policy periodically for any changes.
  
  ### CONTACT US
  
  If you have any questions about this Privacy Policy, please contact us at xghcertification@gmail.com.
  `;

  const deleteAllCookies = () => {
    var cookies = document.cookie.split(";");

    for (var i = 0; i < cookies.length; i++) {
      var cookie = cookies[i];
      var eqPos = cookie.indexOf("=");
      var name = eqPos > -1 ? cookie.substr(0, eqPos) : cookie;
      document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
    }
  };

  return (
    <>
      <Head title="XGH Certification" />
      <h1>
        <a href="https://xgohorse.com">XGH Certification</a>
      </h1>
      <div className="content">
        <ReactMarkdown source={markdown} escapeHtml={false} />
        <h3>Delete Cookies from https://xgohorse.com</h3>
        <button
          onClick={e => {
            e.preventDefault();
            deleteAllCookies();
          }}
        >
          Delete cookies
        </button>
      </div>
      <style jsx>
        {`
          .content {
            display: flex;
            flex-direction: column;
            justify-content: center;
            margin: 0 4rem;
          }
          h1 {
            text-align: center;
          }
          .change-lng {
            position: absolute;
            top: 0;
            right: 0;
          }
        `}
      </style>
    </>
  );
};
